#!/usr/bin/env ruby

require 'belafonte'

class Echo < Belafonte::App

  title "echo"
  summary "Just like system echo"
  description "This prints all of its arguments to the terminal"

  switch :no_newline,
    short: 'n',
    description: "Suppresses the newline at the end of output, except that I want to make this line really long to see what happens when I get help"

  arg :string, times: :unlimited

  def handle
    stdout.print arg(:string).map(&:to_s).join(' ') + newline
  end

  def newline
    switch_active?(:no_newline) ? '' : "\n"
  end
end

exit Echo.new(ARGV).execute!
